"""add title_embedding to tracked_items

Revision ID: df18c4810c4b
Revises: 6890037788c8
Create Date: 2026-09-26 00:42:43.803634

"""

from typing import Sequence, Union

import pgvector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df18c4810c4b"
down_revision: Union[str, None] = "6890037788c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracked_items",
        sa.Column(
            "title_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
    )
    op.alter_column(
        "tracked_items",
        "ticker_or_url",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    op.drop_index("ix_tracked_items_ticker_or_url", table_name="tracked_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_tracked_items_ticker_or_url",
        "tracked_items",
        ["ticker_or_url"],
        unique=False,
    )
    op.alter_column(
        "tracked_items",
        "ticker_or_url",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    op.drop_column("tracked_items", "title_embedding")
    # ### end Alembic commands ###
